---
language: ruby
bundler_args: --without local_only
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.6.0"
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.8.0"
matrix:
  exclude:
    - rvm: 2.4.0
      env: PUPPET_VERSION="~> 4.6.0"
    - rvm: 2.4.0
      env: PUPPET_VERSION="~> 4.7.0"
notifications:
  email:
    recipients:
      - dfarrell@redhat.com
  on_success: change
  on_failure: change
