---
language: ruby
bundler_args: --without local_only
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.7
  - 2.2.3
  - 2.2.6
  - 2.3.1
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.8.0"
matrix:
  exclude:
    - rvm: 2.2.3
      env: PUPPET_VERSION="~> 3.8.0"
    - rvm: 2.2.6
      env: PUPPET_VERSION="~> 3.8.0"
    - rvm: 2.3.1
      env: PUPPET_VERSION="~> 3.8.0"
notifications:
  email:
    recipients:
      - dfarrell@redhat.com
  on_success: change
  on_failure: change
